# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task1

  # Utils

  pod 'SwiftGen', '~> 6.0'

  # UI

  pod 'DeviceKit', '~> 4.0'

end
